# Generated by Django 4.2.10 on 2025-05-23 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterventionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner_type', models.CharField(choices=[('academic', 'Academic'), ('corporate', 'Corporate'), ('government', 'Government'), ('ngo', 'Non-Profit')], default='corporate', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('track', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('workshop', 'Workshop'), ('general', 'General')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('locations', models.ManyToManyField(to='conference_app.interventionlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1)),
                ('countries', models.ManyToManyField(blank=True, to='conference_app.interventionlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='conference_app.session')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.CharField(choices=[('mission', 'Mission'), ('equipment', 'Equipment'), ('banquet', 'Banquet'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('covers_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='conference_app.partner')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='conference_app.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(related_name='sessions', to='conference_app.speaker'),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference_app.attendeetype')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('item_type', models.CharField(choices=[('break', 'Break'), ('lunch', 'Lunch'), ('keynote', 'Keynote'), ('registration', 'Registration'), ('networking', 'Networking'), ('session', 'Session')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='conference_app.session')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('presentation', 'Presentation'), ('keynote', 'Keynote'), ('panel', 'Panel Discussion'), ('moderation', 'Moderation'), ('workshop', 'Workshop')], max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('intervention_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference_app.interventionlocation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_app.session')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_app.speaker')),
            ],
            options={
                'unique_together': {('speaker', 'session')},
            },
        ),
    ]
