# Generated by Django 4.2.10 on 2025-05-23 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersInterventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1)),
                ('intervention_type', models.CharField(choices=[('presentation', 'Presentation'), ('keynote', 'Keynote'), ('panel', 'Panel Discussion'), ('moderation', 'Moderation'), ('workshop', 'Workshop')], max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('intervention_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='speaker_countries', to='conference_app.interventionlocation')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speakers', to='conference_app.interventionlocation')),
            ],
            options={
                'verbose_name': 'Speaker Intervention',
                'verbose_name_plural': 'Speakers Interventions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='speakerintervention',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speakerintervention',
            name='location',
        ),
        migrations.RemoveField(
            model_name='speakerintervention',
            name='session',
        ),
        migrations.RemoveField(
            model_name='speakerintervention',
            name='speaker',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='conference_app.interventionlocation'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='locations',
            field=models.ManyToManyField(related_name='sessions', to='conference_app.interventionlocation'),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='SpeakerIntervention',
        ),
        migrations.AddField(
            model_name='speakersinterventions',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conference_app.session'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='conference_app.speakersinterventions'),
        ),
        migrations.AlterUniqueTogether(
            name='speakersinterventions',
            unique_together={('name', 'session')},
        ),
    ]
