# Generated by Django 5.1.6 on 2025-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0005_remove_agendaitem_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='session_logos/'),
        ),
        
        migrations.AlterField(
            model_name='agendaitem',
            name='item_type',
            field=models.CharField(choices=[('break', 'Break'), ('keynote', 'Keynote'), ('lunch', 'Lunch'), ('networking', 'Networking'), ('registration', 'Registration'), ('session', 'Session')], max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.CharField(choices=[('business', 'Business'), ('general', 'General'), ('technical', 'Technical'), ('workshop', 'Workshop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionfunding',
            name='funding_type',
            field=models.CharField(choices=[('banquet', 'Banquet'), ('equipment', 'Equipment'), ('mission', 'Mission'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='speakersinterventions',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='speakersinterventions',
            name='intervention_type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('moderation', 'Moderation'), ('panel', 'Panel Discussion'), ('presentation', 'Presentation'), ('workshop', 'Workshop')], max_length=20),
        ),
    ]
