# Generated by Django 5.1.6 on 2025-06-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0007_menuphoto_studentvolunteer'),
    ]

    operations = [
    ]
