# Generated by Django 5.1.6 on 2025-06-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0008_fix_migration_conflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery_photos/')),
                ('caption', models.CharField(blank=True, help_text='Courte description ou titre de la photo.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description plus détaillée (optionnel).', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la galerie.")),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='conference_app.session')),
            ],
            options={
                'verbose_name': 'Photo de la Galerie',
                'verbose_name_plural': 'Photos de la Galerie',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('institute', models.CharField(help_text="Université, école ou institut de l'étudiant.", max_length=200)),
                ('role', models.CharField(blank=True, help_text='Rôle spécifique (ex: Accueil, Support Technique...).', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteer_photos/')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la liste.")),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_volunteers', to='conference_app.session')),
            ],
            options={
                'verbose_name': 'Étudiant Volontaire',
                'verbose_name_plural': 'Étudiants Volontaires',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
