# Generated by Django 5.1.6 on 2025-06-25 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0009_menuphoto_studentvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='speaker_intervention',
            field=models.ForeignKey(blank=True, help_text="Link this agenda item to a specific speaker's talk to show their slides.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_entries', to='conference_app.speakersinterventions'),
        ),
        migrations.AddField(
            model_name='speakersinterventions',
            name='slides_file',
            field=models.FileField(blank=True, help_text='PDF of the presentation slides.', null=True, upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='speakersinterventions',
            name='slides_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('confidential', 'Confidential')], default='pending', help_text='Status of the presentation slides.', max_length=20),
        ),
    ]
