# Generated by Django 5.1.6 on 2025-06-25 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0010_agendaitem_speaker_intervention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuphoto',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date à laquelle la photo a été prise.'),
        ),
    ]
