services:
  postgres:
    image: postgres:15
    container_name: postgres_conference_site
    restart: always
    environment:
      POSTGRES_DB: conference_bd
      POSTGRES_USER: romero1
      POSTGRES_PASSWORD: romerotchiaze
    ports:
      - "54323:5432"
    networks:
      - conference_network  # Ce nom est correct
    volumes:
      # Volume nommé pour persister les données
      - postgres_data:/var/lib/postgresql/data
      # Dump uniquement si la DB n'existe pas
      - ./dump_confernce_informatique.sql:/docker-entrypoint-initdb.d/dump_conference_informatique.sql

  site-labo:
    image: lontsi/conference:latest
    container_name: conference-labo
    restart: unless-stopped
    ports:
      - "8023:8000"
    networks:
      - conference_network  # Ce nom est correct
    depends_on:
      - postgres
    stdin_open: true
    tty: true

networks:
  # ▼▼▼▼ LA CORRECTION EST ICI ▼▼▼▼
  # Renommez 'labo_network' en 'conference_network' pour correspondre aux services.
  conference_network:
    driver: bridge
  # ▲▲▲▲ FIN DE LA CORRECTION ▲▲▲▲

# Définir le volume nommé
volumes:
  postgres_data:
    driver: local
