--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Ubuntu 14.17-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.17 (Ubuntu 14.17-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO romero1;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO romero1;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO romero1;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO romero1;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO romero1;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO romero1;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_admin; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_admin (
    id bigint NOT NULL,
    username character varying(150) NOT NULL,
    password character varying(128) NOT NULL,
    is_superuser boolean NOT NULL
);


ALTER TABLE public.conference_app_admin OWNER TO romero1;

--
-- Name: conference_app_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_agendaitem; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_agendaitem (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    item_type character varying(20) NOT NULL,
    location_id bigint,
    session_id bigint
);


ALTER TABLE public.conference_app_agendaitem OWNER TO romero1;

--
-- Name: conference_app_agendaitem_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_agendaitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_agendaitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_attendee; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_attendee (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    company character varying(100) NOT NULL,
    job_title character varying(100) NOT NULL,
    registration_date timestamp with time zone NOT NULL,
    attendee_type_id bigint,
    session_id bigint
);


ALTER TABLE public.conference_app_attendee OWNER TO romero1;

--
-- Name: conference_app_attendee_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_attendee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_attendee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_attendeetype; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_attendeetype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.conference_app_attendeetype OWNER TO romero1;

--
-- Name: conference_app_attendeetype_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_attendeetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_attendeetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_interventionlocation; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_interventionlocation (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    is_primary boolean NOT NULL
);


ALTER TABLE public.conference_app_interventionlocation OWNER TO romero1;

--
-- Name: conference_app_interventionlocation_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_interventionlocation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_interventionlocation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_partner; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_partner (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    logo character varying(100),
    website character varying(200) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    partner_type character varying(20) NOT NULL,
    country character varying(100)
);


ALTER TABLE public.conference_app_partner OWNER TO romero1;

--
-- Name: conference_app_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_session; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_session (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    end_date date NOT NULL,
    track character varying(20) NOT NULL,
    location character varying(100),
    is_hybrid boolean NOT NULL,
    duration_days integer NOT NULL,
    start_date date NOT NULL,
    logo character varying(100),
    CONSTRAINT conference_app_session_duration_days_check CHECK ((duration_days >= 0))
);


ALTER TABLE public.conference_app_session OWNER TO romero1;

--
-- Name: conference_app_session_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_session_locations; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_session_locations (
    id bigint NOT NULL,
    session_id bigint NOT NULL,
    interventionlocation_id bigint NOT NULL
);


ALTER TABLE public.conference_app_session_locations OWNER TO romero1;

--
-- Name: conference_app_session_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_session_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_session_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_sessionfunding; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_sessionfunding (
    id bigint NOT NULL,
    funding_type character varying(20) NOT NULL,
    description text NOT NULL,
    amount numeric(10,2),
    country character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    covers_participants integer,
    partner_id bigint NOT NULL,
    session_id bigint NOT NULL,
    CONSTRAINT conference_app_sessionfunding_covers_participants_check CHECK ((covers_participants >= 0))
);


ALTER TABLE public.conference_app_sessionfunding OWNER TO romero1;

--
-- Name: conference_app_sessionfunding_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_sessionfunding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_sessionfunding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_sessionorganizer; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_sessionorganizer (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    organization character varying(200) NOT NULL,
    "order" integer NOT NULL,
    is_primary boolean NOT NULL,
    session_id bigint NOT NULL,
    photo character varying(100),
    CONSTRAINT conference_app_sessionorganizer_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.conference_app_sessionorganizer OWNER TO romero1;

--
-- Name: conference_app_sessionorganizer_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_sessionorganizer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_sessionorganizer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_speakersinterventions; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_speakersinterventions (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    organization character varying(100) NOT NULL,
    bio text NOT NULL,
    photo character varying(100),
    gender character varying(1) NOT NULL,
    intervention_type character varying(20) NOT NULL,
    is_remote boolean NOT NULL,
    location_id bigint,
    session_id bigint NOT NULL
);


ALTER TABLE public.conference_app_speakersinterventions OWNER TO romero1;

--
-- Name: conference_app_speakersinterventions_countries; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_speakersinterventions_countries (
    id bigint NOT NULL,
    speakersinterventions_id bigint NOT NULL,
    interventionlocation_id bigint NOT NULL
);


ALTER TABLE public.conference_app_speakersinterventions_countries OWNER TO romero1;

--
-- Name: conference_app_speakersinterventions_countries_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_speakersinterventions_countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_speakersinterventions_countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_speakersinterventions_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_speakersinterventions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_speakersinterventions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference_app_subscriber; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.conference_app_subscriber (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    date_subscribed timestamp with time zone NOT NULL
);


ALTER TABLE public.conference_app_subscriber OWNER TO romero1;

--
-- Name: conference_app_subscriber_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.conference_app_subscriber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conference_app_subscriber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO romero1;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO romero1;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO romero1;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: romero1
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: romero1
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO romero1;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add attendee type	7	add_attendeetype
26	Can change attendee type	7	change_attendeetype
27	Can delete attendee type	7	delete_attendeetype
28	Can view attendee type	7	view_attendeetype
29	Can add intervention location	8	add_interventionlocation
30	Can change intervention location	8	change_interventionlocation
31	Can delete intervention location	8	delete_interventionlocation
32	Can view intervention location	8	view_interventionlocation
33	Can add partner	9	add_partner
34	Can change partner	9	change_partner
35	Can delete partner	9	delete_partner
36	Can view partner	9	view_partner
37	Can add session	10	add_session
38	Can change session	10	change_session
39	Can delete session	10	delete_session
40	Can view session	10	view_session
41	Can add subscriber	11	add_subscriber
42	Can change subscriber	11	change_subscriber
43	Can delete subscriber	11	delete_subscriber
44	Can view subscriber	11	view_subscriber
45	Can add session organizer	12	add_sessionorganizer
46	Can change session organizer	12	change_sessionorganizer
47	Can delete session organizer	12	delete_sessionorganizer
48	Can view session organizer	12	view_sessionorganizer
49	Can add session funding	13	add_sessionfunding
50	Can change session funding	13	change_sessionfunding
51	Can delete session funding	13	delete_sessionfunding
52	Can view session funding	13	view_sessionfunding
53	Can add attendee	14	add_attendee
54	Can change attendee	14	change_attendee
55	Can delete attendee	14	delete_attendee
56	Can view attendee	14	view_attendee
57	Can add agenda item	15	add_agendaitem
58	Can change agenda item	15	change_agendaitem
59	Can delete agenda item	15	delete_agendaitem
60	Can view agenda item	15	view_agendaitem
61	Can add Speaker Intervention	16	add_speakersinterventions
62	Can change Speaker Intervention	16	change_speakersinterventions
63	Can delete Speaker Intervention	16	delete_speakersinterventions
64	Can view Speaker Intervention	16	view_speakersinterventions
65	Can add Administrateur	17	add_admin
66	Can change Administrateur	17	change_admin
67	Can delete Administrateur	17	delete_admin
68	Can view Administrateur	17	view_admin
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
3	pbkdf2_sha256$870000$qpiCAqdvnlAB1yGthD5V1n$rMQ1uFNO+mD4VB90J0UsmfI30HM2PvJCjy+ppAVzyVg=	\N	t	Romero				t	t	2025-06-06 13:45:15.036421+01
1	pbkdf2_sha256$870000$5gb4Gn0l26h94FGkCG5FxF$4pF96dge5j1WyHvAYxCnP1d7/rXwIl7Okk51o3Acg64=	2025-06-07 13:02:05.670974+01	t	romeo				t	t	2025-06-06 09:36:06.336664+01
2	pbkdf2_sha256$870000$kvWF8fvEKGj1mUj3WYeIAi$8ETnoLM69t5orfJUAMAO/x9cF/dT0LOQYOyP0I79U3A=	2025-06-18 13:01:09.527537+01	f	romero				f	t	2025-06-06 12:48:21.828228+01
4	pbkdf2_sha256$870000$cXF1RR4iZ4Yfygfz96GLG6$5LgwbndlGVt9a9cIk9lwLGwLnZQuCuyshYOSMXvuMYQ=	2025-06-20 21:33:48.925477+01	t	tchiaze				t	t	2025-06-20 21:33:33.761191+01
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: conference_app_admin; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_admin (id, username, password, is_superuser) FROM stdin;
\.


--
-- Data for Name: conference_app_agendaitem; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_agendaitem (id, title, description, date, start_time, end_time, item_type, location_id, session_id) FROM stdin;
1	Workshop	Accueil des participants	2025-06-24	09:00:00	09:30:00	keynote	1	7
2	Workshop	Anne-Marie Chana (ENSPY)	2025-06-24	09:30:00	10:00:00	keynote	2	7
4	Workshop	Alain Mbo (ENSPY, UGA) et Michèle Mbaha (ENSPY, UGA)	2025-06-24	10:00:00	10:45:00	keynote	3	7
6	Workshop	Emmanuel Monfort (UGA)	2025-06-24	11:30:00	12:00:00	keynote	1	7
5	Workshop	Pause café	2025-06-24	10:45:00	11:00:00	break	3	7
7	Workshop	Blandine Ntchoutta (Univ. Douala, UGA) et Christian Kamdoum	2025-06-24	11:00:00	11:30:00	keynote	3	7
8	Workshop	Pause repas	2025-06-24	12:00:00	14:00:00	lunch	3	7
9	Workshop	Lawrence Ayong (Centre Pasteur Cameroun)	2025-06-24	14:00:00	14:30:00	keynote	2	7
10	Workshop	Marcelle Abanda (Centre Pasteur Cameroun), Pascal Petit (UGA)	2025-06-24	14:30:00	15:15:00	keynote	3	7
11	Workshop	Pause	2025-06-24	15:15:00	15:30:00	break	3	7
12	Workshop	Nicolas Vuillerme (UGA)	2025-06-24	15:30:00	16:00:00	keynote	1	7
13	Workshop	Discussion collaboration (thèses cotutelles)	2025-06-24	16:00:00	17:00:00	networking	3	7
14	Workshop	Welcome of participants	2025-06-25	08:30:00	09:00:00	break	3	7
15	Workshop	Robotics day participation	2025-06-25	09:00:00	12:00:00	session	1	7
16	Workshop	Bernabé Batchakui (ENSPY)	2025-06-25	14:00:00	14:30:00	keynote	2	7
17	Workshop	Donald Onana (UY1, IMT Atlantique) et Jules Seban (UGA)	2025-06-25	14:30:00	15:15:00	keynote	3	7
18	Workshop	Break	2025-06-25	15:15:00	15:30:00	break	3	7
19	Workshop	Nnanga Nga (UY1, IRAD)	2025-06-25	15:30:00	16:00:00	keynote	2	7
20	Workshop	cotutelle theses, international relations - IR	2025-06-25	16:00:00	17:00:00	networking	3	7
21	Workshop	Social event	2025-06-25	17:00:00	19:00:00	session	3	7
22	Workshop	Banquet	2025-06-25	19:00:00	21:00:00	lunch	1	7
23	Workshop	Welcome of participants	2025-06-26	09:00:00	09:30:00	break	1	7
24	Workshop	Parfait Bessala (UY1)	2025-06-26	09:30:00	10:00:00	keynote	2	7
25	Workshop	Medecin doctorant 1 (UGA) et Medecin doctorant 2 (UGA)	2025-06-26	10:00:00	10:45:00	keynote	1	7
26	Workshop	Pause café	2025-06-26	10:30:00	11:00:00	break	3	7
27	Workshop	Josiane Kouam (Inria)	2025-06-26	11:00:00	11:30:00	keynote	1	7
28	Workshop	Brice Ekane (Univ. Rennes)	2025-06-26	11:30:00	12:00:00	keynote	1	7
29	Workshop	Break Lunch	2025-06-26	12:00:00	14:00:00	lunch	1	7
30	Workshop	Cyril Wyon-Boyault (Reckonect)	2025-06-26	14:00:00	14:30:00	keynote	1	7
31	Workshop	Fred Fabo (OFTY)	2025-06-26	14:30:00	15:00:00	keynote	3	7
32	Workshop	Louis Closson (UGA)	2025-06-26	15:00:00	15:30:00	keynote	1	7
33	Workshop	Samuel Bayiha (Ministère des marchés publics Cameroun)	2025-06-26	15:30:00	16:00:00	keynote	2	7
34	Workshop	cotutelle theses, international relations - IR	2025-06-26	16:00:00	17:00:00	networking	1	7
\.


--
-- Data for Name: conference_app_attendee; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_attendee (id, name, email, company, job_title, registration_date, attendee_type_id, session_id) FROM stdin;
\.


--
-- Data for Name: conference_app_attendeetype; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_attendeetype (id, name, description) FROM stdin;
\.


--
-- Data for Name: conference_app_interventionlocation; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_interventionlocation (id, name, country, is_primary) FROM stdin;
2	Yaounde Cameroun	CM	f
1	Grenoble France	FR	t
3	France&Cameroun	FR	f
\.


--
-- Data for Name: conference_app_partner; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_partner (id, name, logo, website, description, is_active, created_at, partner_type, country) FROM stdin;
1	Erasmus	partners/erasmus.png		une mission Cameroun -> France	t	2025-06-21 12:57:29.865807+01	corporate	\N
2	IRB	partners/IRB.jpeg		(UGA International Research Booster IAoundé): Cameroun -> France	t	2025-06-21 13:02:25.832819+01	corporate	\N
3	LIG	partners/lig.png		demande financement d'une mission Cameroun -> France	t	2025-06-21 13:03:09.260313+01	corporate	\N
\.


--
-- Data for Name: conference_app_session; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_session (id, title, description, end_date, track, location, is_hybrid, duration_days, start_date, logo) FROM stdin;
5	Data science	test	2025-07-14	technical	Yaounde	f	8	2025-07-07	
7	Workshop IRP CNRS MLNS2	Conference sur l'OS	2025-06-26	workshop	Yaounde	f	3	2025-06-24	session_logos/logo_HqtGXic.jpg
\.


--
-- Data for Name: conference_app_session_locations; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_session_locations (id, session_id, interventionlocation_id) FROM stdin;
3	5	1
\.


--
-- Data for Name: conference_app_sessionfunding; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_sessionfunding (id, funding_type, description, amount, country, created_at, covers_participants, partner_id, session_id) FROM stdin;
\.


--
-- Data for Name: conference_app_sessionorganizer; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_sessionorganizer (id, name, organization, "order", is_primary, session_id, photo) FROM stdin;
9	Alain Tchana	Grenoble INP - UGA	0	t	7	organizer_photos/Pr_Tchana.jpeg
10	Nicolas Vuillerme	UGA	1	f	7	organizer_photos/Nicolas.jpeg
11	Anne Chana	ENSP	3	f	7	organizer_photos/photo_2025-06-21_08-34-20.jpg
12	Parfat Bessala	UY1	4	f	7	organizer_photos/photo_2025-06-21_08-34-15.jpg
13	Bernabé Batchakui	ENSP	5	f	7	organizer_photos/photo_2025-06-21_08-34-34.jpg
\.


--
-- Data for Name: conference_app_speakersinterventions; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_speakersinterventions (id, name, title, organization, bio, photo, gender, intervention_type, is_remote, location_id, session_id) FROM stdin;
4	Parfat Bessala	DSI	UY1-FMSB		speakers/photo_2025-06-21_08-34-15.jpg	U	presentation	f	\N	7
5	Bernabé Batchakui	Professeur	ENSP		speakers/photo_2025-06-21_08-34-34.jpg	U	presentation	f	\N	7
6	Anne Chana	Docteur	ENSPY		speakers/photo_2025-06-21_08-34-20.jpg	U	presentation	f	\N	7
7	Samuel Bayiha	Docteur	Ministère des marchés publics		speakers/photo_2025-06-21_08-34-25.jpg	U	presentation	f	\N	7
8	Lawrence Ayong	Docteur	Centre Pasteur		speakers/photo_2025-06-21_08-34-30.jpg	U	presentation	f	\N	7
9	Alain Mbo	Computer Engineering student	ENSPY, UGA		speakers/Alain_Mbo.jpeg	U	presentation	f	\N	7
10	Michèle Mbaha	Computer Engineering student	ENSPY, UGA		speakers/photo_2025-06-21_13-35-32.jpg	U	presentation	f	\N	7
11	Donald Onana	phd student	UY1, IMT Atlantique		speakers/Donald_Onana.jpeg	U	presentation	f	\N	7
12	Fred Fabo	Founder OFTY	OFTY		speakers/Fred_Fabo.jpeg	U	presentation	f	\N	7
13	Marcelle Abanda	TLAM at Centre Pasteur	Centre Pasteur		speakers/photo_2025-06-21_13-35-32_VSGogfE.jpg	U	presentation	f	\N	7
14	Christian Kamdoum	Computer Engineering student	Grenoble INP		speakers/photo_2025-06-21_13-35-35.jpg	U	presentation	f	\N	7
15	Emmanuel Monfort	Professor	UGA		speakers/Emmanuel_Monfort.jpg	U	presentation	f	\N	7
16	Jules Seban	Computer Engineering student	(UGA		speakers/photo_2025-06-21_13-35-35_U37dzBM.jpg	U	presentation	f	\N	7
17	Medecin doctorant 1	Computer Engineering student	(UGA		speakers/photo_2025-06-21_13-35-35_Nb2VD1P.jpg	U	presentation	f	\N	7
18	Medecin doctorant 2	Computer Engineering student	(UGA		speakers/photo_2025-06-21_13-35-35_u6aQW1l.jpg	U	presentation	f	\N	7
19	osiane Kouam	Postdoctoral Researcher	Inria		speakers/Anne-Josiane-Kouam.jpg	U	presentation	f	\N	7
20	Brice Ekane	Associate professor of Computer science	Univ. Rennes		speakers/Brice-Ekane.jpg	U	presentation	f	\N	7
21	Cyril Wyon-Boyault	SIO at Reckonect	Reckonect		speakers/Cyril_Wyon-Boyault.jpeg	U	presentation	f	\N	7
22	Louis Closson	Ing. Phd in AI	UGA		speakers/Louis-Closson.jpg	U	presentation	f	\N	7
\.


--
-- Data for Name: conference_app_speakersinterventions_countries; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_speakersinterventions_countries (id, speakersinterventions_id, interventionlocation_id) FROM stdin;
\.


--
-- Data for Name: conference_app_subscriber; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.conference_app_subscriber (id, email, date_subscribed) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-06-06 09:43:03.607125+01	1	Paris, France	1	[{"added": {}}]	8	1
2	2025-06-06 12:48:23.403833+01	2	romero	1	[{"added": {}}]	4	1
3	2025-06-20 21:56:12.273901+01	2	romero (uy1)	1	[{"added": {}}]	12	4
4	2025-06-20 22:04:15.804608+01	3	seminaire compilation	1	[{"added": {}}]	10	4
5	2025-06-20 22:22:27.392181+01	4	test1	1	[{"added": {}}]	10	4
6	2025-06-20 22:25:19.299755+01	2	Os for IA	2	[{"changed": {"fields": ["Start date", "End date", "Location"]}}]	10	4
7	2025-06-20 22:26:53.449592+01	2	Os for IA	2	[{"changed": {"fields": ["Is hybrid"]}}]	10	4
8	2025-06-20 22:27:41.124235+01	2	Os for IA	2	[{"changed": {"fields": ["Start date"]}}]	10	4
9	2025-06-21 08:20:15.711247+01	1	AI for OS	3		10	4
10	2025-06-21 08:20:15.711333+01	6	Session de test	3		10	4
11	2025-06-21 16:06:49.58621+01	2	Os for IA	3		10	4
12	2025-06-21 16:06:49.586312+01	3	seminaire compilation	3		10	4
13	2025-06-21 16:06:49.586374+01	4	test1	3		10	4
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	conference_app	attendeetype
8	conference_app	interventionlocation
9	conference_app	partner
10	conference_app	session
11	conference_app	subscriber
12	conference_app	sessionorganizer
13	conference_app	sessionfunding
14	conference_app	attendee
15	conference_app	agendaitem
16	conference_app	speakersinterventions
17	conference_app	admin
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-06-06 09:32:15.061574+01
2	auth	0001_initial	2025-06-06 09:32:16.882119+01
3	admin	0001_initial	2025-06-06 09:32:17.158757+01
4	admin	0002_logentry_remove_auto_add	2025-06-06 09:32:17.194082+01
5	admin	0003_logentry_add_action_flag_choices	2025-06-06 09:32:17.216317+01
6	contenttypes	0002_remove_content_type_name	2025-06-06 09:32:17.276382+01
7	auth	0002_alter_permission_name_max_length	2025-06-06 09:32:17.318589+01
8	auth	0003_alter_user_email_max_length	2025-06-06 09:32:17.362218+01
9	auth	0004_alter_user_username_opts	2025-06-06 09:32:17.395683+01
10	auth	0005_alter_user_last_login_null	2025-06-06 09:32:17.423211+01
11	auth	0006_require_contenttypes_0002	2025-06-06 09:32:17.435942+01
12	auth	0007_alter_validators_add_error_messages	2025-06-06 09:32:17.462894+01
13	auth	0008_alter_user_username_max_length	2025-06-06 09:32:17.54899+01
14	auth	0009_alter_user_last_name_max_length	2025-06-06 09:32:17.592811+01
15	auth	0010_alter_group_name_max_length	2025-06-06 09:32:17.618392+01
16	auth	0011_update_proxy_permissions	2025-06-06 09:32:17.649595+01
17	auth	0012_alter_user_first_name_max_length	2025-06-06 09:32:17.677315+01
18	conference_app	0001_initial	2025-06-06 09:32:20.684762+01
19	conference_app	0002_speakersinterventions_and_more	2025-06-06 09:32:22.230402+01
20	conference_app	0003_remove_speakersinterventions_end_time_and_more	2025-06-06 09:32:22.331591+01
21	conference_app	0004_alter_session_options_attendee_session_and_more	2025-06-06 09:32:22.557757+01
22	conference_app	0005_remove_agendaitem_speaker	2025-06-06 09:32:22.601517+01
23	sessions	0001_initial	2025-06-06 09:32:22.878875+01
24	conference_app	0006_sessionorganizer_photo	2025-06-06 10:07:41.349669+01
25	conference_app	0007_admin	2025-06-06 12:46:26.699981+01
26	conference_app	0008_admin_is_superuser	2025-06-06 13:21:05.214418+01
27	conference_app	0006_session_logo_sessionorganizer_photo_and_more	2025-06-20 21:22:03.570724+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: romero1
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
oa4kszce1is0ystia0soadlorcqcv59j	.eJxVjEEOwiAQRe_C2hAGKDAu3XuGZsowtmpKUtqV8e7apAvd_vfef6metnXst1aWfmJ1VqBOv9tA-VHmHfCd5lvVuc7rMg16V_RBm75WLs_L4f4djNTGb22YyQYW5yCZDtFni8gEhksAAfEBEkqXBV2KRiwZA9khRhtzl7yo9wfSozcj:1uNsFR:dP-7IvFho1tF2zbQ-42Gfk2QOl6YnXIb61lKawwKzms	2025-06-21 13:02:05.763265+01
rpnty3h4jf5owsveo2u76fu8g0yi8ghp	.eJxVjEEOwiAQRe_C2pBSEGZcuu8ZCDCMVA0kpV0Z765NutDtf-_9l_BhW4vfel78TOIijDj9bjGkR647oHuotyZTq-syR7kr8qBdTo3y83q4fwcl9PKtmcasbLasyLKzJhHk6M6j46AhOMCYSFujQSMAqiEqTmoANOgsOs3i_QHymjd5:1uSiQm:99qgc2BR4sHvsc3qRkWEd8zw0NW3lWXeM-YjQfxer6o	2025-07-04 21:33:48.994367+01
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: conference_app_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_admin_id_seq', 1, false);


--
-- Name: conference_app_agendaitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_agendaitem_id_seq', 34, true);


--
-- Name: conference_app_attendee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_attendee_id_seq', 1, true);


--
-- Name: conference_app_attendeetype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_attendeetype_id_seq', 1, false);


--
-- Name: conference_app_interventionlocation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_interventionlocation_id_seq', 3, true);


--
-- Name: conference_app_partner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_partner_id_seq', 3, true);


--
-- Name: conference_app_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_session_id_seq', 7, true);


--
-- Name: conference_app_session_locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_session_locations_id_seq', 4, true);


--
-- Name: conference_app_sessionfunding_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_sessionfunding_id_seq', 1, false);


--
-- Name: conference_app_sessionorganizer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_sessionorganizer_id_seq', 13, true);


--
-- Name: conference_app_speakersinterventions_countries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_speakersinterventions_countries_id_seq', 2, true);


--
-- Name: conference_app_speakersinterventions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_speakersinterventions_id_seq', 22, true);


--
-- Name: conference_app_subscriber_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.conference_app_subscriber_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 13, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: romero1
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: conference_app_admin conference_app_admin_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_admin
    ADD CONSTRAINT conference_app_admin_pkey PRIMARY KEY (id);


--
-- Name: conference_app_admin conference_app_admin_username_key; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_admin
    ADD CONSTRAINT conference_app_admin_username_key UNIQUE (username);


--
-- Name: conference_app_agendaitem conference_app_agendaitem_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_agendaitem
    ADD CONSTRAINT conference_app_agendaitem_pkey PRIMARY KEY (id);


--
-- Name: conference_app_attendee conference_app_attendee_email_key; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_attendee
    ADD CONSTRAINT conference_app_attendee_email_key UNIQUE (email);


--
-- Name: conference_app_attendee conference_app_attendee_email_session_id_09a5c876_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_attendee
    ADD CONSTRAINT conference_app_attendee_email_session_id_09a5c876_uniq UNIQUE (email, session_id);


--
-- Name: conference_app_attendee conference_app_attendee_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_attendee
    ADD CONSTRAINT conference_app_attendee_pkey PRIMARY KEY (id);


--
-- Name: conference_app_attendeetype conference_app_attendeetype_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_attendeetype
    ADD CONSTRAINT conference_app_attendeetype_pkey PRIMARY KEY (id);


--
-- Name: conference_app_interventionlocation conference_app_interventionlocation_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_interventionlocation
    ADD CONSTRAINT conference_app_interventionlocation_pkey PRIMARY KEY (id);


--
-- Name: conference_app_partner conference_app_partner_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_partner
    ADD CONSTRAINT conference_app_partner_pkey PRIMARY KEY (id);


--
-- Name: conference_app_session_locations conference_app_session_l_session_id_interventionl_9c8d1dc3_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_session_locations
    ADD CONSTRAINT conference_app_session_l_session_id_interventionl_9c8d1dc3_uniq UNIQUE (session_id, interventionlocation_id);


--
-- Name: conference_app_session_locations conference_app_session_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_session_locations
    ADD CONSTRAINT conference_app_session_locations_pkey PRIMARY KEY (id);


--
-- Name: conference_app_session conference_app_session_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_session
    ADD CONSTRAINT conference_app_session_pkey PRIMARY KEY (id);


--
-- Name: conference_app_sessionfunding conference_app_sessionfunding_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_sessionfunding
    ADD CONSTRAINT conference_app_sessionfunding_pkey PRIMARY KEY (id);


--
-- Name: conference_app_sessionorganizer conference_app_sessionorganizer_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_sessionorganizer
    ADD CONSTRAINT conference_app_sessionorganizer_pkey PRIMARY KEY (id);


--
-- Name: conference_app_speakersinterventions conference_app_speakersi_name_session_id_25005510_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions
    ADD CONSTRAINT conference_app_speakersi_name_session_id_25005510_uniq UNIQUE (name, session_id);


--
-- Name: conference_app_speakersinterventions_countries conference_app_speakersi_speakersinterventions_id_9558a7e2_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions_countries
    ADD CONSTRAINT conference_app_speakersi_speakersinterventions_id_9558a7e2_uniq UNIQUE (speakersinterventions_id, interventionlocation_id);


--
-- Name: conference_app_speakersinterventions_countries conference_app_speakersinterventions_countries_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions_countries
    ADD CONSTRAINT conference_app_speakersinterventions_countries_pkey PRIMARY KEY (id);


--
-- Name: conference_app_speakersinterventions conference_app_speakersinterventions_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions
    ADD CONSTRAINT conference_app_speakersinterventions_pkey PRIMARY KEY (id);


--
-- Name: conference_app_subscriber conference_app_subscriber_email_key; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_subscriber
    ADD CONSTRAINT conference_app_subscriber_email_key UNIQUE (email);


--
-- Name: conference_app_subscriber conference_app_subscriber_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_subscriber
    ADD CONSTRAINT conference_app_subscriber_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: conference_app_admin_username_c7e8dba0_like; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_admin_username_c7e8dba0_like ON public.conference_app_admin USING btree (username varchar_pattern_ops);


--
-- Name: conference_app_agendaitem_location_id_450fbb2c; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_agendaitem_location_id_450fbb2c ON public.conference_app_agendaitem USING btree (location_id);


--
-- Name: conference_app_agendaitem_session_id_f3ae1be6; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_agendaitem_session_id_f3ae1be6 ON public.conference_app_agendaitem USING btree (session_id);


--
-- Name: conference_app_attendee_attendee_type_id_9dd144c9; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_attendee_attendee_type_id_9dd144c9 ON public.conference_app_attendee USING btree (attendee_type_id);


--
-- Name: conference_app_attendee_email_86cd17de_like; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_attendee_email_86cd17de_like ON public.conference_app_attendee USING btree (email varchar_pattern_ops);


--
-- Name: conference_app_attendee_session_id_876dabf3; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_attendee_session_id_876dabf3 ON public.conference_app_attendee USING btree (session_id);


--
-- Name: conference_app_session_loc_interventionlocation_id_97162c36; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_session_loc_interventionlocation_id_97162c36 ON public.conference_app_session_locations USING btree (interventionlocation_id);


--
-- Name: conference_app_session_locations_session_id_fbdd1057; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_session_locations_session_id_fbdd1057 ON public.conference_app_session_locations USING btree (session_id);


--
-- Name: conference_app_sessionfunding_partner_id_03449c47; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_sessionfunding_partner_id_03449c47 ON public.conference_app_sessionfunding USING btree (partner_id);


--
-- Name: conference_app_sessionfunding_session_id_d87bf9c0; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_sessionfunding_session_id_d87bf9c0 ON public.conference_app_sessionfunding USING btree (session_id);


--
-- Name: conference_app_sessionorganizer_session_id_f3c680ef; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_sessionorganizer_session_id_f3c680ef ON public.conference_app_sessionorganizer USING btree (session_id);


--
-- Name: conference_app_speakersint_interventionlocation_id_8378226e; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_speakersint_interventionlocation_id_8378226e ON public.conference_app_speakersinterventions_countries USING btree (interventionlocation_id);


--
-- Name: conference_app_speakersint_speakersinterventions_id_b4eef127; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_speakersint_speakersinterventions_id_b4eef127 ON public.conference_app_speakersinterventions_countries USING btree (speakersinterventions_id);


--
-- Name: conference_app_speakersinterventions_location_id_5b5bb435; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_speakersinterventions_location_id_5b5bb435 ON public.conference_app_speakersinterventions USING btree (location_id);


--
-- Name: conference_app_speakersinterventions_session_id_61590587; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_speakersinterventions_session_id_61590587 ON public.conference_app_speakersinterventions USING btree (session_id);


--
-- Name: conference_app_subscriber_email_a0020ee3_like; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX conference_app_subscriber_email_a0020ee3_like ON public.conference_app_subscriber USING btree (email varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: romero1
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_agendaitem conference_app_agend_location_id_450fbb2c_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_agendaitem
    ADD CONSTRAINT conference_app_agend_location_id_450fbb2c_fk_conferenc FOREIGN KEY (location_id) REFERENCES public.conference_app_interventionlocation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_agendaitem conference_app_agend_session_id_f3ae1be6_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_agendaitem
    ADD CONSTRAINT conference_app_agend_session_id_f3ae1be6_fk_conferenc FOREIGN KEY (session_id) REFERENCES public.conference_app_session(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_attendee conference_app_atten_attendee_type_id_9dd144c9_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_attendee
    ADD CONSTRAINT conference_app_atten_attendee_type_id_9dd144c9_fk_conferenc FOREIGN KEY (attendee_type_id) REFERENCES public.conference_app_attendeetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_attendee conference_app_atten_session_id_876dabf3_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_attendee
    ADD CONSTRAINT conference_app_atten_session_id_876dabf3_fk_conferenc FOREIGN KEY (session_id) REFERENCES public.conference_app_session(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_session_locations conference_app_sessi_interventionlocation_97162c36_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_session_locations
    ADD CONSTRAINT conference_app_sessi_interventionlocation_97162c36_fk_conferenc FOREIGN KEY (interventionlocation_id) REFERENCES public.conference_app_interventionlocation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_sessionfunding conference_app_sessi_partner_id_03449c47_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_sessionfunding
    ADD CONSTRAINT conference_app_sessi_partner_id_03449c47_fk_conferenc FOREIGN KEY (partner_id) REFERENCES public.conference_app_partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_sessionfunding conference_app_sessi_session_id_d87bf9c0_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_sessionfunding
    ADD CONSTRAINT conference_app_sessi_session_id_d87bf9c0_fk_conferenc FOREIGN KEY (session_id) REFERENCES public.conference_app_session(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_sessionorganizer conference_app_sessi_session_id_f3c680ef_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_sessionorganizer
    ADD CONSTRAINT conference_app_sessi_session_id_f3c680ef_fk_conferenc FOREIGN KEY (session_id) REFERENCES public.conference_app_session(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_session_locations conference_app_sessi_session_id_fbdd1057_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_session_locations
    ADD CONSTRAINT conference_app_sessi_session_id_fbdd1057_fk_conferenc FOREIGN KEY (session_id) REFERENCES public.conference_app_session(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_speakersinterventions_countries conference_app_speak_interventionlocation_8378226e_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions_countries
    ADD CONSTRAINT conference_app_speak_interventionlocation_8378226e_fk_conferenc FOREIGN KEY (interventionlocation_id) REFERENCES public.conference_app_interventionlocation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_speakersinterventions conference_app_speak_location_id_5b5bb435_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions
    ADD CONSTRAINT conference_app_speak_location_id_5b5bb435_fk_conferenc FOREIGN KEY (location_id) REFERENCES public.conference_app_interventionlocation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_speakersinterventions conference_app_speak_session_id_61590587_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions
    ADD CONSTRAINT conference_app_speak_session_id_61590587_fk_conferenc FOREIGN KEY (session_id) REFERENCES public.conference_app_session(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conference_app_speakersinterventions_countries conference_app_speak_speakersintervention_b4eef127_fk_conferenc; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.conference_app_speakersinterventions_countries
    ADD CONSTRAINT conference_app_speak_speakersintervention_b4eef127_fk_conferenc FOREIGN KEY (speakersinterventions_id) REFERENCES public.conference_app_speakersinterventions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: romero1
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

