# Generated by Django 4.2.10 on 2025-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_speakersinterventions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakersinterventions',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='speakersinterventions',
            name='intervention_date',
        ),
        migrations.RemoveField(
            model_name='speakersinterventions',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='session',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='conference_app.interventionlocation'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(),
        ),
    ]
