# Generated by Django 4.2.10 on 2025-05-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0003_remove_speakersinterventions_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='attendee',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='conference_app.session'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('email', 'session')},
        ),
    ]
