# Generated by Django 4.2.10 on 2025-05-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0004_alter_session_options_attendee_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='speaker',
        ),
    ]
