# Generated by Django 4.2.10 on 2025-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0006_session_logo_sessionorganizer_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionorganizer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_photos/'),
        ),
    ]
